name: Deploy Members Forum

on:
  push:
    branches:
      - main  # or your deployment branch
  pull_request:

jobs:
  validate-html:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install HTML Validator
        run: npm install -g htmlhint

      - name: Run HTML Validation
        run: htmlhint ./path-to-your-html/MembersForum.html

  deploy-to-gh-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: validate-html
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './'  # Adjust if your HTML lives in a subfolder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
